---
app:
  name: Granite
  tagline: Your Self-Hosted Knowledge Base
server:
  host: 0.0.0.0
  port: 8000
  reload: false
  allowed_origins:
    - '*'
  debug: true
  https_only: false
storage:
  notes_dir: ./data
  plugins_dir: ./plugins
  templates_dir: custom_templates
  homepage_file: README.md
search:
  enabled: true
authentication:
  enabled: false
  secret_key: change_this_to_a_random_secret_key_in_production
  password_hash: $2b$12$t/6PGExFzdpU2PUta0iVY.eDQwvu63kH.c/d4bEnnHaQ5CspH1yrG
  session_max_age: 604800
